[project]
name = "object-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "deep-sort-realtime>=1.3.2",
    "filterpy>=1.4.5",
    "opencv-python>=4.11.0.86",
    "ultralytics>=8.3.129",
]
